name: wtech_design_system

description: "A new Flutter Design System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  google_fonts:
    git:
      url: https://github.com/material-foundation/google-fonts-flutter.git
      ref: main
      path: packages/google_fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/design_system/assets/svgs/